"""Destination-aware activity estimates generated by DeepSeek."""
from ._ai import ESTIMATE_NOTE, coordinates, estimated_record, generate_json, number, string_list, text
from ._geography import destination_allows_retired_tokyo_places, retired_tokyo_record_field

SYSTEM_PROMPT = (
    "You generate activity candidates for a trip planner. Every activity must physically belong "
    "to the exact requested destination or be a realistic day trip explicitly departing from it. "
    "Never substitute another city/country. Return ONLY JSON: {options: [{name, style, price, "
    "duration, area, lat, lng, tags}], reasoning}. Return at least requested_count distinct options, "
    "with no duplicate or repeat visits. Match activity styles and budget. Prices are estimates in "
    "the requested currency; names/hours require verification."
)


def _fallback(destination: str, styles: list[str], count: int) -> list[dict]:
    ideas = [
        ("Historic center walking exploration", "cultural", 0, "2h"),
        ("Local museum or cultural institution", "cultural", 20, "2h"),
        ("Neighborhood food and market walk", "relaxed", 30, "2.5h"),
        ("City viewpoint and skyline visit", "relaxed", 18, "1.5h"),
        ("Regional nature day trip", "adventure", 65, "Full day"),
        ("Local craft workshop", "cultural", 45, "2h"),
        ("Waterfront or park exploration", "relaxed", 0, "2h"),
        ("Guided cycling or hiking experience", "adventure", 55, "3h"),
    ]
    options = []
    for index in range(count):
        name, style, price, duration = ideas[index % len(ideas)]
        options.append(estimated_record({
            "id": f"activity_{index + 1}",
            "name": f"{destination}: {name} {index // len(ideas) + 1 if index >= len(ideas) else ''}".strip(),
            "style": style if style in styles or not styles else styles[index % len(styles)],
            "price": price,
            "duration": duration,
            "area": f"{destination} — verify neighborhood",
            "tags": ["destination-specific", "verify"],
        }, destination))
    return options


def get_activity_options(
    destination: str,
    activity_styles: list[str] | None = None,
    requested_count: int = 6,
    budget: dict | None = None,
    time_constraints: str = "",
) -> list[dict]:
    styles = activity_styles or []
    count = max(4, min(int(requested_count), 21))
    result = generate_json(SYSTEM_PROMPT, {
        "destination": destination,
        "activity_styles": styles,
        "requested_count": count,
        "budget": budget or {},
        "time_constraints": time_constraints,
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.55)

    options = []
    seen = set()
    for raw in (result or {}).get("options", []):
        if not isinstance(raw, dict):
            continue
        if (
            not destination_allows_retired_tokyo_places(destination)
            and retired_tokyo_record_field(raw)
        ):
            continue
        name = text(raw.get("name"))
        if not name or name.casefold() in seen:
            continue
        seen.add(name.casefold())
        option = {
            "id": f"activity_{len(options) + 1}",
            "name": name,
            "style": text(raw.get("style"), styles[0] if styles else "cultural").lower(),
            "price": round(number(raw.get("price"), 0), 2),
            "duration": text(raw.get("duration"), "2h"),
            "area": text(raw.get("area"), destination),
            "tags": string_list(raw.get("tags"), ["verify"]),
        }
        lat, lng = coordinates(raw)
        if lat is not None:
            option.update({"lat": lat, "lng": lng})
        options.append(estimated_record(option, destination))
        if len(options) >= count:
            break
    if len(options) < count:
        existing_names = {option["name"].casefold() for option in options}
        for fallback in _fallback(destination, styles, count):
            if fallback["name"].casefold() not in existing_names:
                options.append(fallback)
                existing_names.add(fallback["name"].casefold())
            if len(options) >= count:
                break
    for index, option in enumerate(options[:count], start=1):
        option["id"] = f"activity_{index}"
    return options[:count]
