"""Destination-aware cost estimates generated by DeepSeek."""
from functools import lru_cache

from ._ai import ESTIMATE_NOTE, generate_json, number, text

SYSTEM_PROMPT = (
    "Estimate travel costs for the exact requested destination and origin. Never reuse figures or "
    "places from another city. Return ONLY JSON with keys: currency, cost_level, daily_index "
    "({food, activity, housing, local_transport}), flight_reference, reasoning. Use the requested "
    "currency. These are planning estimates, not live quotes."
)


@lru_cache(maxsize=128)
def _generate(destination: str, origin: str, start: str, end: str, currency: str) -> dict:
    result = generate_json(SYSTEM_PROMPT, {
        "destination": destination,
        "origin": origin,
        "dates": {"start": start, "end": end},
        "currency": currency,
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.3)
    raw_daily = (result or {}).get("daily_index", {})
    if not isinstance(raw_daily, dict):
        raw_daily = {}
    return {
        "currency": currency,
        "cost_level": text((result or {}).get("cost_level"), "AI-estimated"),
        "daily_index": {
            "food": round(number(raw_daily.get("food"), 55), 2),
            "activity": round(number(raw_daily.get("activity"), 45), 2),
            "housing": round(number(raw_daily.get("housing"), 140), 2),
            "local_transport": round(number(raw_daily.get("local_transport"), 18), 2),
        },
        "flight_reference": round(number((result or {}).get("flight_reference"), 850), 2),
        "reasoning": text((result or {}).get("reasoning"), f"Generic estimates used for {destination}."),
        "destination": destination,
        "source": "deepseek_estimate" if result else "generic_estimate",
        "verification_required": True,
        "estimate_note": ESTIMATE_NOTE,
    }


def get_cost_index(
    destination: str,
    origin: str = "",
    dates: dict | None = None,
    currency: str = "USD",
) -> dict:
    dates = dates or {}
    return _generate(destination, origin, dates.get("start", ""), dates.get("end", ""), currency)
