"""Destination-aware transportation estimates generated by DeepSeek.

This is not live inventory. Replace this implementation with a flight/rail API
later while preserving the returned shape.
"""
from ._ai import ESTIMATE_NOTE, estimated_record, generate_json, integer, number, text

SYSTEM_PROMPT = (
    "You generate transportation candidates for a trip planner. Use ONLY the requested origin, "
    "destination, dates, currency, and transport preferences. Never substitute another city or "
    "country. Produce plausible route estimates, not claims of live schedules or availability. "
    "Return ONLY JSON: {options: [{carrier, mode, price, duration, departure_time, "
    "arrival_airport, stops}], reasoning}. Return 3 varied options. Prices are round-trip estimates "
    "in the requested currency. If rail/car is geographically unrealistic, omit it."
)


def _fallback(origin: str, destination: str, transport_types: list[str]) -> list[dict]:
    mode = (transport_types or ["flight"])[0]
    base = 850 if mode == "flight" else 240
    return [
        estimated_record({
            "id": f"transport_{index}",
            "carrier": f"{mode.title()} option {index} — verify provider",
            "mode": mode,
            "price": base + (index - 2) * 120,
            "duration": "Schedule unavailable — verify",
            "departure_time": "Verify",
            "arrival_airport": f"{destination} arrival point — verify",
            "stops": max(index - 1, 0),
            "origin": origin,
        }, destination)
        for index in range(1, 4)
    ]


def get_flight_options(
    origin: str,
    destination: str,
    dates: dict,
    budget: dict | None = None,
    transport_types: list[str] | None = None,
) -> list[dict]:
    transport_types = transport_types or ["flight"]
    result = generate_json(SYSTEM_PROMPT, {
        "origin": origin,
        "destination": destination,
        "dates": dates,
        "budget": budget or {},
        "currency": (budget or {}).get("currency", "USD"),
        "transport_preferences": transport_types,
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.35)

    raw_options = (result or {}).get("options", [])
    options = []
    for index, raw in enumerate(raw_options[:5], start=1):
        if not isinstance(raw, dict):
            continue
        options.append(estimated_record({
            "id": f"transport_{index}",
            "carrier": text(raw.get("carrier"), f"Transport option {index}"),
            "mode": text(raw.get("mode"), transport_types[0]).lower(),
            "price": round(number(raw.get("price"), 850), 2),
            "duration": text(raw.get("duration"), "Verify duration"),
            "departure_time": text(raw.get("departure_time"), "Verify"),
            "arrival_airport": text(raw.get("arrival_airport"), f"{destination} arrival point"),
            "stops": integer(raw.get("stops"), 0),
            "origin": origin,
        }, destination))
    return options if len(options) >= 2 else _fallback(origin, destination, transport_types)
