"""Destination-aware dining estimates generated by DeepSeek."""
from ._ai import ESTIMATE_NOTE, estimated_record, generate_json, number, string_list, text

CUISINE_ALIASES = {
    "japanese": {"japanese", "sushi", "ramen", "izakaya", "tempura", "japanese curry"},
    "chinese": {"chinese", "cantonese", "sichuan", "dim sum"},
    "korean": {"korean", "korean bbq"},
    "thai": {"thai"},
    "indian": {"indian"},
    "italian": {"italian", "pizza", "pasta"},
    "mexican": {"mexican", "tacos"},
    "american": {"american", "burgers", "bbq", "diner"},
    "mediterranean": {"mediterranean", "greek", "levantine"},
    "french": {"french", "bistro"},
}

SYSTEM_PROMPT = (
    "Generate dining candidates located in the exact requested destination. Never return a venue "
    "from another city or country. Honor ONLY the selected cuisine families when they are supplied. "
    "Return ONLY JSON: {options: [{name, cuisine, cuisine_family, price, meal_type, area, rating, "
    "tags}], reasoning}. meal_type is breakfast, lunch, or dinner. Return requested_count varied "
    "options with enough choices in every meal slot and avoid duplicate names. Prices are estimates "
    "in the requested currency. If unsure a named venue exists, use a descriptive dining experience "
    "ending in '(verify)' instead of inventing a confident factual claim."
)


def matches_cuisine_preferences(option: dict, cuisine_tags: list[str] | None) -> bool:
    if not cuisine_tags:
        return True
    wanted = {tag.casefold() for tag in cuisine_tags}
    family = text(option.get("cuisine_family")).casefold()
    cuisine = text(option.get("cuisine")).casefold()
    if family:
        if family in wanted:
            return True
        return any(cuisine in CUISINE_ALIASES.get(selected, {selected}) for selected in wanted)
    expanded = set(wanted)
    for selected in wanted:
        expanded.update(CUISINE_ALIASES.get(selected, set()))
    haystack = {cuisine, *[tag.casefold() for tag in option.get("tags", [])]}
    return bool(haystack & expanded)


_SLOT_WEIGHTS = {"breakfast": 0.25, "lunch": 0.35, "dinner": 0.40}


def _slot_budget(daily_budget: float | None, slot: str) -> float | None:
    if daily_budget is None or daily_budget <= 0:
        return None
    return round(daily_budget * _SLOT_WEIGHTS[slot], 2)


def _fallback(
    destination: str,
    cuisine_tags: list[str],
    count: int,
    daily_budget: float | None = None,
) -> list[dict]:
    families = cuisine_tags or ["Local"]
    slots = ["breakfast", "lunch", "dinner"]
    formats = {
        "breakfast": "bakery or grocery breakfast",
        "lunch": "market or counter-service lunch",
        "dinner": "simple takeaway or self-catered dinner",
    }
    options = []
    for index in range(count):
        family = families[index % len(families)]
        slot = slots[index % len(slots)]
        slot_price = _slot_budget(daily_budget, slot)
        options.append(estimated_record({
            "id": f"food_{index + 1}",
            "name": f"{destination} {family} {formats[slot]} {index + 1} (verify)",
            "cuisine": family,
            "cuisine_family": family,
            "price": slot_price if slot_price is not None else {
                "breakfast": 15,
                "lunch": 24,
                "dinner": 40,
            }[slot],
            "meal_type": slot,
            "area": f"{destination} — verify neighborhood",
            "rating": 0,
            "tags": [family.lower(), "verify"],
        }, destination))
    return options


def get_food_options(
    destination: str,
    cuisine_tags: list[str] | None = None,
    num_days: int = 5,
    budget: dict | None = None,
    preferences: dict | None = None,
    time_constraints: str = "",
    daily_budget: float | None = None,
) -> list[dict]:
    cuisines = cuisine_tags or []
    count = max(12, min(int(num_days) * 3, 42))
    result = generate_json(SYSTEM_PROMPT, {
        "destination": destination,
        "selected_cuisines_in_priority_order": cuisines,
        "requested_count": count,
        "num_days": num_days,
        "budget": budget or {},
        "food_budget_per_day": daily_budget,
        "per_meal_budget_limits": {
            slot: _slot_budget(daily_budget, slot)
            for slot in ("breakfast", "lunch", "dinner")
        } if daily_budget else None,
        "budget_rule": (
            "Every candidate price must fit its per-meal limit. Offer realistic low-cost formats "
            "such as bakeries, markets, counter service, groceries, or self-catering when needed."
        ) if daily_budget else None,
        "all_preferences": preferences or {},
        "time_constraints": time_constraints,
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.6)

    options = []
    seen = set()
    for raw in (result or {}).get("options", []):
        if not isinstance(raw, dict):
            continue
        name = text(raw.get("name"))
        slot = text(raw.get("meal_type")).lower()
        if not name or name.casefold() in seen or slot not in {"breakfast", "lunch", "dinner"}:
            continue
        family = text(raw.get("cuisine_family"), text(raw.get("cuisine"), cuisines[0] if cuisines else "Local"))
        option = estimated_record({
            "id": f"food_{len(options) + 1}",
            "name": name,
            "cuisine": text(raw.get("cuisine"), family),
            "cuisine_family": family,
            "price": round(number(raw.get("price"), 25), 2),
            "meal_type": slot,
            "area": text(raw.get("area"), destination),
            "rating": min(number(raw.get("rating"), 0), 5.0),
            "tags": string_list(raw.get("tags"), [family.lower(), "verify"]),
        }, destination)
        if cuisines and not matches_cuisine_preferences(option, cuisines):
            continue
        slot_limit = _slot_budget(daily_budget, slot)
        if slot_limit is not None and option["price"] > slot_limit:
            continue
        seen.add(name.casefold())
        options.append(option)
        if len(options) >= count:
            break

    required_per_slot = count // 3
    fallback_options = _fallback(destination, cuisines, count, daily_budget)
    completed = []
    for slot in ("breakfast", "lunch", "dinner"):
        slot_options = [option for option in options if option["meal_type"] == slot]
        slot_names = {option["name"].casefold() for option in slot_options}
        slot_options.extend(
            item for item in fallback_options
            if item["meal_type"] == slot and item["name"].casefold() not in slot_names
        )
        completed.extend(slot_options[:required_per_slot])
    for index, option in enumerate(completed, start=1):
        option["id"] = f"food_{index}"
    return completed
