"""Destination-aware lodging estimates generated by DeepSeek."""
from ._ai import ESTIMATE_NOTE, coordinates, estimated_record, generate_json, number, string_list, text

SYSTEM_PROMPT = (
    "You generate lodging candidates for a trip planner. Use ONLY the requested destination and "
    "dates. Never return a property or neighborhood from another destination. Return ONLY JSON: "
    "{options: [{name, price_per_night, rating, area, lat, lng, tags}], reasoning}. Return 6 varied "
    "choices across budget, mid-range, and premium levels that fit the traveler's preferences. "
    "Use plausible known properties when confident; otherwise describe a stay concept and append "
    "'(verify)'. Prices are estimates in the requested currency, never live availability."
)


def _fallback(destination: str) -> list[dict]:
    templates = [("Value stay", 85, 4.0), ("Central hotel", 150, 4.3), ("Premium stay", 260, 4.6)]
    return [estimated_record({
        "id": f"hotel_{index}",
        "name": f"{destination} {label} (verify)",
        "price_per_night": price,
        "rating": rating,
        "area": f"Central {destination} — verify area",
        "tags": [label.lower(), "verify"],
    }, destination) for index, (label, price, rating) in enumerate(templates, start=1)]


def get_hotel_options(
    destination: str,
    dates: dict,
    max_price_per_night: float | None = None,
    budget: dict | None = None,
    preferences: dict | None = None,
) -> list[dict]:
    result = generate_json(SYSTEM_PROMPT, {
        "destination": destination,
        "dates": dates,
        "budget": budget or {},
        "max_price_per_night": max_price_per_night,
        "traveler_preferences": preferences or {},
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.45)

    options = []
    for index, raw in enumerate((result or {}).get("options", [])[:8], start=1):
        if not isinstance(raw, dict):
            continue
        option = {
            "id": f"hotel_{index}",
            "name": text(raw.get("name"), f"{destination} stay {index} (verify)"),
            "price_per_night": round(number(raw.get("price_per_night"), 150), 2),
            "rating": min(number(raw.get("rating"), 4.0), 5.0),
            "area": text(raw.get("area"), f"{destination} center"),
            "tags": string_list(raw.get("tags"), ["verify"]),
        }
        lat, lng = coordinates(raw)
        if lat is not None:
            option.update({"lat": lat, "lng": lng})
        options.append(estimated_record(option, destination))

    options = options if len(options) >= 3 else _fallback(destination)
    if max_price_per_night is not None:
        affordable = [option for option in options if option["price_per_night"] <= max_price_per_night]
        return affordable or [min(options, key=lambda option: option["price_per_night"])]
    return options
