"""Destination-aware weather outlook generated by DeepSeek.

Without a weather API this is explicitly a seasonal planning estimate, not a
forecast. It is still tied to the requested destination and exact dates.
"""
from datetime import date, timedelta

from ._ai import ESTIMATE_NOTE, generate_json, number, text

SYSTEM_PROMPT = (
    "Create a seasonal weather planning outlook for the exact destination and dates. Never use "
    "another city's climate. This is not live forecast data. Return ONLY JSON: {summary, daily: "
    "[{date, condition, high_c, low_c, rain_chance}]}. Include every requested date exactly once. "
    "rain_chance is a decimal from 0 to 1. The summary must explicitly say 'AI seasonal estimate'."
)


def _days(dates: dict) -> list[str]:
    start = date.fromisoformat(dates["start"])
    end = date.fromisoformat(dates["end"])
    if end < start:
        start, end = end, start
    values = []
    while start <= end:
        values.append(start.isoformat())
        start += timedelta(days=1)
    return values


def get_weather(destination: str, dates: dict) -> dict:
    requested_days = _days(dates)
    result = generate_json(SYSTEM_PROMPT, {
        "destination": destination,
        "dates": dates,
        "requested_dates": requested_days,
        "truthfulness_requirement": ESTIMATE_NOTE,
    }, temperature=0.35)

    raw_by_date = {
        item.get("date"): item
        for item in (result or {}).get("daily", [])
        if isinstance(item, dict) and item.get("date") in requested_days
    }
    daily = []
    for requested_date in requested_days:
        raw = raw_by_date.get(requested_date, {})
        high = number(raw.get("high_c"), 20, minimum=-60)
        low = number(raw.get("low_c"), 12, minimum=-70)
        daily.append({
            "date": requested_date,
            "condition": text(raw.get("condition"), "Seasonal conditions — verify"),
            "high_c": round(high, 1),
            "low_c": round(min(low, high), 1),
            "rain_chance": min(number(raw.get("rain_chance"), 0.3), 1.0),
            "source": "deepseek_seasonal_estimate",
        })

    summary = text((result or {}).get("summary"), f"{destination}: AI seasonal estimate; verify closer to departure.")
    if "ai seasonal estimate" not in summary.lower():
        summary = f"AI seasonal estimate for {destination}: {summary} Verify closer to departure."
    return {
        "summary": summary,
        "daily": daily,
        "source": "deepseek_seasonal_estimate",
        "verification_required": True,
        "estimate_note": ESTIMATE_NOTE,
    }
